### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by uestchjw** [tum-traffic-dataset/coopdet3d#4]
**I want to install coopdet3d without docker. However, after installing all the required dependencies, I run** 
`python setup.py develop`
**An error occurs.** 
`TypeError: expected string or bytes-like object`
**I don't know why. The whole error information is as follows.**

> (coopdet3d) root@zgc-a6000-114-41:/mnt/data/hjw/Code/coopdet3d# python setup.py develop
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.7'
Compiling bev_pool_ext without CUDA
Compiling iou3d_cuda without CUDA
Compiling voxel_layer without CUDA
Compiling roiaware_pool3d_ext without CUDA
Compiling ball_query_ext without CUDA
Compiling knn_ext without CUDA
Compiling assign_score_withk_ext without CUDA
Compiling group_points_ext without CUDA
Compiling interpolate_ext without CUDA
Compiling furthest_point_sample_ext without CUDA
Compiling gather_points_ext without CUDA
running develop
/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    setup(
  File "/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File "/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 436, in build_extensions
    self._check_cuda_version(compiler_name, compiler_version)
  File "/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 813, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 49, in parse
    return Version(version)
  File "/home/taizun/anaconda3/envs/coopdet3d/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

**Comment by uestchjw** [comment]
I think I know why there was an error. **The reason is torchsparse.**
Generally we will use the method from **_https://pypi.org/project/torch-sparse/_** to install torchsparse, which is 
`conda install pytorch-sparse -c pyg`
However, this command will install pytorch-1.12.1, which conflicts with our previous installation pytorch-1.9.1 (or other versions).
So we should uninstall torch and install the needed pytorch version after installing "torchsparse".

**Comment by uestchjw** [comment]
I'm sorry that I should install **"torchsparse"** but not **"torch-sparse"**.
The correct installation guidance is **https://torchsparse-docs.github.io/getting_started/installation.html**.
